services:
  yolov5-inference:
    build:
      context: .
      dockerfile: Dockerfile
    image: yolov5-inference:latest
    container_name: yolov5-inference
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./models:/app/models
      - ./input:/app/input
      - ./merged_clothing.yaml:/app/merged_clothing.yaml
      - ./clo_values.yaml:/app/clo_values.yaml
      - ./clo_processor.py:/app/clo_processor.py
    environment:
      - PYTHONUNBUFFERED=1
